all:
  hosts:
    ec2-3-236-142-147.compute-1.amazonaws.com:
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/aws_openclassrooms_devops_p6.pem
      ansible_python_interpreter: /usr/bin/python3.12

