all:
  children:
    webservers:  # Groupe pour les serveurs web : un seul serveur ici mais prévoyons ...
      hosts:
        # eip: public dns
        ec2-35-180-1-165.eu-west-3.compute.amazonaws.com:
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/aws_openclassrooms_devops_p6.pem
          ansible_python_interpreter: /usr/bin/python3.12
    #Anticiper d'autres serveurs en répartissant en groupe  

