all:
  children:
    webgcp:
      hosts:
        # Utilisez l'IP publique ou le DNS de votre VM GCP
        34.155.216.222:
          ansible_user: daniel
          ansible_ssh_private_key_file: ~/.ssh/id_ocp6exo2gcp
          ansible_python_interpreter: /usr/bin/python3

